version: '3.9'

services:
  server:
    restart: always
    build: .
    ports:
      - '4000:4000'
    links:
      - mongo
    volumes:
      - .:/urs/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - mongo
      
  mongo:
    restart: always
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=restaurantSearchEngine
    ports:
      - '27017:27017'